### ISSUE TITLE
Scaling is incorrect, from newer versions of Inkscape. Selects 25.4DPI instead of 90DPI

### ISSUE THREAD

**Issue by kd5ftn** [stefanix/LasaurApp#66]
Here's some testing and results, based on behavior seen by [@lukeiamyourfather, @hasbridge and myself, @Nick_McCarthy at the Dallas Makerspace] (https://talk.dallasmakerspace.org/t/lasersaur-and-svg-scaling/5724)

When using recent versions of Inkscape or other vector drawing apps, upon importing to the Lasersaur, the file is scaled much larger.

You can see in the example below that my shape is off the bed, and the lasersaur shows it's using **25.4DPI for converting unit pixels**
<img src="https://talk.dallasmakerspace.org/uploads/default/original/2X/5/514d4e92dc0b3274cf2877fa44a7ce5adf5f4e12.png" width="690" height="388">

When making the same identical document in the old version of Inkscape on the computer next to the lasersaur, the file imports properly, showing **90DPI**
<img src="https://talk.dallasmakerspace.org/uploads/default/original/2X/6/69afed64d9e88e6aadf4ddc89577937157e6adfa.png" width="690" height="388">

So, the difference?

In the new version (I have .91), we see this in the SVG

    width="1220mm"
    height="610mm"
    viewBox="0 0  4322.8345 2161.4173"

In the older version (v.48), this is in the SVG:

    width="4322.8345"
    height="2161.4172"

**So, the fix:**
Modify the SVG from the newer version of inkscape, and move "4322.8345 2161.4173" from viewbox into width and height, the file will print just fine.

 - Option 1: Open the SVG in a text editor and do this manually
 - Option 2: Write a script automates this process
 - Option 3: Get this fix merged into the Lasersaur code.

**Comment by kd5ftn** [comment]
I stumbled across the Google Group discussing this issue as well:
https://groups.google.com/forum/m/#!msg/lasersaur/5L9B5JvyEPw/NHfeVEXQ3-YJ

**Comment by markvdb** [comment]
The right fix would of course be to modify the svg parsing on the lasaurapp
side to accept the (more correct) .91 generated svg files...

2015-10-08 9:13 GMT+02:00 kd5ftn <notifications@github.com>:

> I stumbled across the Google Group discussing this issue as well:
> https://groups.google.com/forum/m/#!msg/lasersaur/5L9B5JvyEPw/NHfeVEXQ3-YJ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stefanix/LasaurApp/issues/66#issuecomment-146440564>.
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by martinxyz** [comment]
This commit https://github.com/stefanix/LasaurApp/commit/0888d8b4d titled "some changes how to recognize mm units in Inkscape 0.91 files" is already part of the master branch 2015-02-02. I thought this was working. Can you confirm that your LasaurApp checkout is up-to-date?

There is also a patch in the google group discussion (linked above), which doesn't seem to be finished and not part of master.

**Comment by stefanix** [comment]
@kd5ftn 0.91 is comfirmed to work with LasaurApp. Make sure you have the current version by ssh'ing into the Driveboard and running a git pull in the LasaurApp folder. You may also have to set the page dimensions in Inkscape to 1220x610mm. The svg should have a viewbox like this:

viewBox="0 0 1220 610"

There is also a nice Inkscape template you can install:
http://www.lasersaur.com/manual/inkscape

**Comment by k5njm** [comment]
Thanks Stefanix, 

I'm having my team @ the Makerspace update the Lasersaur software and we'll test again (We're likely a version behind). Very good to know about the template!
