### ISSUE TITLE
DPI calculation wrong in some cases

### ISSUE THREAD

**Issue by bullestock** [stefanix/LasaurApp#72]
As I also reported on the mailing list:

I have created the attached file in Inkscape.

Looking at the file, you can see

```
   width="1220mm"
   height="610mm"
     units="mm"
```

so all should be well. The 't's in the file have a height of 4.021 mm according to Inkscape.

When loading the file into LasaurApp, without forcing a DPI, the log says:

```
    You uploaded torsten.svg (18180 bytes).
    INFO:svg_reader:SVG w,h (unit) is 1220.0,610.0 (mm).
    INFO:svg_reader:px2mm by svg mm unit
```

and in the browser I get " Using 25 for converting units.". BUT the imported objects are definitely not the right size! See attached screen shot. The text gets shown at approx. 18 mm height - but if I force a DPI of 90, I get the correct size.
[example.zip](https://github.com/stefanix/LasaurApp/files/250671/example.zip)

**Comment by martinxyz** [comment]
Your SVG file doesn't have a "viewbox" element. In Inkscape, you can fix this by creating a new document and then import (not open) your original file. If you open and then save again, inkscape will not modify the header.

Not sure if it is possible to fix this without guesswork - without he "viewbox" you cannot really know what "width" and "height" refer to (all other units in the file are in pixels).

**Comment by bullestock** [comment]
@martinxyz: Thanks for clearing this up.
